### ISSUE TITLE
question: is it possible to authenticate without using the Android mobile app?

### ISSUE THREAD

**Issue by monperrus** [virtualforce/bankid-authentication#1]
I'm looking for to a 100% bankid authentication on Linux.

This tutorial is super interesting, contains very valuable information, but requires to use an Android app in addition.

Do you know a way to skip the Android app?

**Comment by m-umer-asif** [comment]
Hey Martin,

Sure. You can use the desktop version of the BankID authentication app.
Unfortunately the desktop application is only available for Windows and Mac
systems.
I don't know how useful this information is for you, but I am happy that
you liked the tutorial. If you have any other question(s), feel free to ask!

Regards,
Umer


On Dec 10, 2017 6:53 PM, "Martin Monperrus" <notifications@github.com>
wrote:

I'm looking for to a 100% bankid authentication on Linux.

This tutorial is super interesting, contains very valuable information, but
requires to use an Android app in addition.

Do you know a way to skip the Android app?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/virtualforce/bankid-authentication/issues/1>, or mute
the thread

**Comment by monperrus** [comment]
Hey Umer,

Thanks a lot for your super fast answer.

For a 100% Linux solution, I can use neither the mobile app nor the Windows or Mac desktop client. 

What protocol do those desktop clients use? Is it documented somewhere?

**Comment by m-umer-asif** [comment]
Hey Martin,

Unfortunately no. The apps are provided by the BankID company. There is no
documentation that I am aware of regarding the apps. They don't discuss
what protocol they use, or how they authenticate the incoming request.
All they show in their docs is how to authenticate.

On Dec 10, 2017 7:07 PM, "Martin Monperrus" <notifications@github.com>
wrote:

Hey Umer,

Thanks a lot for your super fast answer.

For a 100% Linux solution, I can use neither the mobile app nor the Windows
or Mac desktop client.

What protocol does those desktop clients use? Is it documented somewhere?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/virtualforce/bankid-authentication/issues/1#issuecomment-350550764>,
or mute the thread
